### ISSUE TITLE
Release process

### ISSUE THREAD

**Issue by kimmoal** [keydet89/RegRipper3.0#11]
Hello,

thank you for the useful tool, we at the CinCan project (https://cincan.io) are packaging open source tools used for DFIR, and your tool is also included in our toolset (https://gitlab.com/CinCan/tools/-/tree/master/stable/regripper)

We are also tracking releases, but your release process makes things very difficult, so may I give some pointers to help us keep us updated.

1. Please do not change repo name when making a release, it breaks our automatic tracking of updates and we have to manually update this repository
2. Make a GitHub release when making a release. This is essentially a tagging a commit and marking it as a release in GitHub.

This will help us automate the update process greatly.

Thanks!

**Comment by keydet89** [comment]
Thank you.
