### ISSUE TITLE
Regripper 2.8 plugins

### ISSUE THREAD

**Issue by randomaccess3** [keydet89/RegRipper3.0#12]
Hi,
Is there somewhere that the old 2.8 plugins can reside so that I can port over the old ones as needed, or just review for stored information?
I'm looking specifically for a plugin that I wrote and stored in that repository related to webroot registry artefacts
Thanks

**Comment by keydet89** [comment]
Plugins for RR 2.8 can reside anywhere, and you can even run them from the RR 3.0 plugins folder.

**Comment by randomaccess3** [comment]
![image](https://user-images.githubusercontent.com/1241363/96336661-13b68180-10cd-11eb-8449-43b33e6cd6dd.png)

Ok that's great to know

But one of the ones that I'm looking for I added to your repository erroneously thinking that it would remain online. 
It appears that this is not available on GitHub and I was wondering if it has been deleted, whether you have a previous version of the repository before it was deleted, or it has just been marked as private.

If it has been marked as private, can you please allow me to fork it temporarily so that I can get a copy of the plugin that I mentioned in the issue that I'm looking for

Thank you

**Comment by keydet89** [comment]
Sorry, I misunderstood.  

From http://windowsir.blogspot.com/2020/05/tips-on-using-regripper-v30.html:

"RegRipper v2.8
As a final note and just a reminder, I'm no longer supporting RegRipper v2.8.  I'll leave the repo up for the time being, but I'll be removing the repo before too long (date TBD)."

The repo isn't marked private, it's no longer available.

What did the plugin in question extract from the Registry?  Maybe I can help with that.

**Comment by randomaccess3** [comment]
Great
Thanks

**Comment by keydet89** [comment]
What did the plugin in question extract from the Registry? Maybe I can help with that.

**Comment by randomaccess3** [comment]
You'd have to get a copy of the webroot AV and look at the way in which it stores detections.

Or consult the plugin that I thought to share. I should have a copy of it somewhere but I should have transitioned it from rr2.8 to 3.0 earlier. Didn't know it could just be copied from one to the other without modification, but then that begs the question why didn't you do that prior to deleting the plugin repository?

**Comment by keydet89** [comment]
"...look at the way in which it stores detections."

Ah, okay...that's cool.  I already covered that on my own.  WebRoot AV storing detections in the Software hive was something I saw this past spring, and wrote my own plugin.

Also, it seems that there's something in the malware.pl plugin, as well.

#  20161210 - added WebRoot check

"...begs the question why didn't you do that prior to deleting the plugin repository?"

Honestly, I didn't know to do so.  I kept the local repo I maintained, but I'm not a Github or SVN guru, and have tried seeking assistance from the community when I've had questions.
