### ISSUE TITLE
* Feature Request * - A 'clear' button in rr.exe

### ISSUE THREAD

**Issue by MrHobbits** [keydet89/RegRipper3.0#14]
When we import a hive and Rip! the status display area does what it is expected to do. However, if we Rip! another hive the status display area does not clear.  Two things of note

1. You can't CTRL+A in the status area to select all and then delete it manually
2. A "clear" button somewhere on the window to clear that box before we Rip! (or, just clear the display box each run?)

**Comment by keydet89** [comment]
I think I've found a solution...

**Comment by keydet89** [comment]
Update pushed to the repo.
