### ISSUE TITLE
Error: Can't call method "is_dirty" on an undefined value C:\Users\[user]\.\RegRipper3.0-master\rr.exe line 498

### ISSUE THREAD

**Issue by MCH7977** [keydet89/RegRipper3.0#17]
Received this error while attempting to parse an NTUSER.dat file. I will use Registry Explorer to receive a "clean" copy of the registry hive and see if this error persists. 

![image](https://user-images.githubusercontent.com/73905209/98585136-d2ad2980-2294-11eb-90be-dc96b9685e0c.png)

**Comment by keydet89** [comment]
Can you share a copy of the NTUSER.DAT hive?  Or, can you try using rip.exe to check to see if the hive is dirty?

**Comment by MCH7977** [comment]
> Can you share a copy of the NTUSER.DAT hive? Or, can you try using rip.exe to check to see if the hive is dirty?

I think it may be a corrupted hive... sorry about that. Feel free to close this

**Comment by keydet89** [comment]
Done
