### ISSUE TITLE
LastWrite Timestamp of usb plugin is incorrect!

### ISSUE THREAD

**Issue by frankwxu** [keydet89/RegRipper3.0#18]
The test dd image is from https://www.cfreds.nist.gov/data_leakage_case/data-leakage-case.html

![image](https://user-images.githubusercontent.com/1145258/102905557-55eb9e80-4441-11eb-8cc5-d84f42f93919.png)

**Comment by MrHobbits** [comment]
Harlan,

Looking over /Key.pm I see that you set _timestamp to unpack_windows_time($timestamp), but I can't find anywhere where you converted it to Z (UTC). The little I know of Perl, I did some stackoverflow/exchange searches and it seems you need to use something like    "gmtime get_timestamp()"    in your functions to pull Zulu time. Without frankwxu posting some additional information I'm having a tough time isolating if it's a PICNIC issue or Plugin issue.

**Comment by keydet89** [comment]
Key LastWrite times are stored in UTC format.  I don't believe this is an issue with the tool.

**Comment by keydet89** [comment]
Key LastWrite times are stored in UTC format.  I don't believe this is an issue with the tool.
