### ISSUE TITLE
Latest rr.exe identifies UsrClass.dat files as NTUSER hives 

### ISSUE THREAD

**Issue by CmdrBurrito** [keydet89/RegRipper3.0#28]
Hi, unsure if this was the intended behavior, but when running the latest "rr.exe" against UsrClass.dat hive files, it appears that the exe always identifies/classifies any USRCLASS hives as NTUSER hives.  In doing so, the "rr.exe" ends up unnecessarily running all of the non-applicable NTUSER hive specific plugins against any USRCLASS hives.  Unfortunately, I believe only two (2) of the current NTUSER hive plugins are actually designed to also work with UsrClass.DAT files.  As a result, the output files for any "rr.exe" processed USRCLASS hives, end up being filled with tons of useless NTUSER hive specific plugin headers with no other underlying output.  Can "rr.exe" be adjusted so that USRCLASS hives are specifically recognized, and only applicable RR plugins are run against them?

**Comment by keydet89** [comment]
Can you share examples of these USRCLASS hives?

**Comment by CmdrBurrito** [comment]
I just stumbled across a single USRCLASS hive on the host I'm looking at, that DID get properly identified as a USRCLASS hive.  It was the one for the "Default" account on this particular Win10 v1909 system, however, the USRCLASS hives for all other accounts on this machine are still being misidentified as NTUSER hives.  Freaky.

Regrettably, I do not believe I am free to supply you with a copy of the hive files... at least not via a public forum.  Can I help in some other way?

**Comment by keydet89** [comment]
For the USRCLASS hives that are misidentified as NTUSER hives, what happens when you run the following rip command against them:

rip -r <path_to_hive> -g

What response do you get for the files?

**Comment by CmdrBurrito** [comment]
Interesting, the supplied "rip" command returns "usrclass" in all cases.

However, when I open the exact same USRCLASS hives in "rr.exe" it's still misidentifying them as NTUSER.

Just let me how I can be of further assistance.

**Comment by keydet89** [comment]
I've got some thoughts as to what I can do to potentially address this issue; let me try something, and I'll get back to you.  Unfortunately, all of the USRCLASS hives I have available are correctly identified by both tools.

**Comment by keydet89** [comment]
I pushed updates to rr.pl/.exe this morning, give it a shot and let me know if it works.  Thanks!

**Comment by CmdrBurrito** [comment]
Hi Harlan,

Awesome, whatever you did fixed it!  It's working like a charm now!  :)

All of my "UsrClass.dat" files are now being properly ID'd as USRCLASS hives by "rr".

Best Regards!
