### ISSUE TITLE
Can't find COM object hijacking.

### ISSUE THREAD

**Issue by unk0unk0unk0** [keydet89/RegRipper3.0#3]
I'd like to add inprocserver plugin to usrclass profile. It was removed from the latest version.

**Comment by keydet89** [comment]
You can copy a plugin from the 2.8 distro into the plugins folder for the 3.0 distro and run it without any issues.  The only difference will be the date format.  This may be a viable immediate solution for you, until the plugin can be "ported over".  

HTH

**Comment by unk0unk0unk0** [comment]
Of course I know it. However, I need to execute inprocserver plugin with other plugins included in usrclass profile at once. Therefore, I would like you to add inprocserver plugin to usrclass profile.

**Comment by keydet89** [comment]
> ...I would like you to add inprocserver plugin to usrclass profile.

You can.  

1. Copy plugin to plugins folder.

2a. Run "rip -uP" 

...or...

2b. Open profile "usrclass" in a text editor and add the name of the plugin to the profile.

HTH.
