### ISSUE TITLE
Add new plugin specifically for WinRM

### ISSUE THREAD

**Issue by Karneades** [keydet89/RegRipper3.0#33]
Plugin idea: plugin dedicated to get WinRM service state and WinRM features.

Some registry keys are already available in the ryuk plugin
https://github.com/keydet89/RegRipper3.0/blob/05ef95773b2b417d0a3e14382f6002c0a57db6c3/plugins/ryuk_gpo.pl#L74

**Comment by keydet89** [comment]
Do you have any specific info, and example data available?

**Comment by Karneades** [comment]
E.g. reading HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WinRM and the start and type value.
And we could add the mapping from https://www.itprotoday.com/compute-engines/what-are-errorcontrol-start-and-type-values-under-services-subkeys in the plugin output as help or just add the link, as used with the SSIDs in the SAM plugin.

**Comment by Karneades** [comment]
I'm not able to provide sample data currently.

**Comment by keydet89** [comment]
"reading HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WinRM and the start and type value."

That's already available via the Services plugin.

"...as used with the SSIDs in the SAM plugin."

The SAM plugin doesn't include SSIDs...although the plugin related to Wifi connections does...is that the one you were referring to?

**Comment by Karneades** [comment]
Oh, yes, of course, the service plugin would provide all of it.

I meant SID, not SSID, sorry for the typo. https://github.com/keydet89/RegRipper3.0/blob/05ef95773b2b417d0a3e14382f6002c0a57db6c3/plugins/samparse.pl#L213
