### ISSUE TITLE
Plugin idea: PortProxy values

### ISSUE THREAD

**Issue by Karneades** [keydet89/RegRipper3.0#35]
Hi Harlan

A plugin for PortProxy registry key would be cool - one or multiple values could be there.
```
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\PortProxy\v4tov4\tcp\*
```
Command to trigger an addition
```
# create
netsh interface portproxy add v4tov4 listenport=1337 listenaddress=0.0.0.0 connectport=3389 connectaddress=10.2.0.12

# query
reg.exe query HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\PortProxy\v4tov4\tcp

# remove again
netsh interface portproxy delete v4tov4 listenport=1337 listenaddress=0.0.0.0
```` 

References:
* https://www.fireeye.com/blog/threat-research/2019/01/bypassing-network-restrictions-through-rdp-tunneling.html
* https://adepts.of0x.cc/netsh-portproxy-code/
* https://www.dfirnotes.net/portproxy_detection/
* Sigma PR for the key: https://github.com/SigmaHQ/sigma/pull/1569/files 

Cheers
Andreas

**Comment by keydet89** [comment]
I've got one in the Pro version of RegRipper, thanks.

**Comment by Karneades** [comment]
You mention Pro version once more... I never read about that. What did I miss?

**Comment by keydet89** [comment]
I've had a tweet pinned to my Twitter profile since April that mentions this.

**Comment by Karneades** [comment]
I don't use Twitter actively... but thanks for the hint. Don't see anything there despite the rdp shadowing tweet mentioning a Pro version. Where do I find information regarding this version?

**Comment by Karneades** [comment]
If I write the plugin by myself and make a PR, would you merge it or won't you because of the Pro version?

**Comment by keydet89** [comment]
I've described the functionality during OSDFCon presentations.

**Comment by keydet89** [comment]
As you can see from Github, others have written plugins that I've merged.

**Comment by Karneades** [comment]
Re: OSDFcon: Went through https://www.osdfcon.org/events_2020/effectively-using-regripper-3-0/ and https://www.youtube.com/watch?v=rkzXyqa5e1g but didn't anything related to a Pro version. I leave it that way. It's fine.

And regarding plugins, of course I know that you merge things, but I asked because of your mention of "already in Pro version".

**Comment by Karneades** [comment]
Thanks for your additions, really appreciated. I use RR since many years and still rely on the tool on a weekly basis, but never saw a PRO version or what that means. I read/heard in the OSDFCon presentation about some new features, as you described in your comment above, but I'm not sure what "having a plugin in a pro version" means.

Where is that PRO plugin repo and who is able to use that?

I don't need a MITRE mapping and I'm more thank thankful of your efforts on your blog and books regarding analysis tips. And the way reg ripper works is excellent for my work.

In general, if one finds a new registry key, then today, if one would like to contribute back, one has to make PR for RegRipper, Registry Explorer (Bookmark), forensic artifact repo, Sigma rule, MISP events, ... difficult to keep up with everything :)

**Comment by keydet89** [comment]
> ...I'm not sure what "having a plugin in a pro version" means.

It means I'm developing the Pro version of RegRipper, and it hasn't been publicly released.

> Where is that PRO plugin repo and who is able to use that?

On my hard drive.

> ...difficult to keep up with everything :)

Not really...pick one.  

I wrote what became RegRipper in 2007, and released it as "RegRipper" in 2008.  Since then, I have not seen more than a very few people find something new and even consider writing a RegRipper plugin.
