### ISSUE TITLE
After update rip.pl not working

### ISSUE THREAD

**Issue by sidomir7** [keydet89/RegRipper3.0#39]
After last update script rip.pl not working properly in linux. 
It afected linux distros like sift.

**Comment by keydet89** [comment]
Do you know which update it was?

**Comment by sidomir7** [comment]
Hi, sorry for late response. The newest update broke it. Where the script path variable and plugin directory and path variables were added.

**Comment by sidomir7** [comment]
Version 20210612 - not working
Version 20210302 - working ok

**Comment by keydet89** [comment]
Okay, let me see what I can do...give me a day or two.

**Comment by keydet89** [comment]
Okay, reverted rip.pl back to Version 20210302. I'll be careful about considering further updates to path building...
