### ISSUE TITLE
Missing executed flag in appcompatcache plugin output

### ISSUE THREAD

**Issue by Karneades** [keydet89/RegRipper3.0#40]
I miss the "executed" flag in the output of the [appcompatcache](https://github.com/keydet89/RegRipper3.0/blob/master/plugins/appcompatcache.pl) plugin. Signature is `0x80` and the server is a `Windows Server 2012 R2 Standard`. It's also missing for a Windows 10 machine (sig `0x34`).

I will now try to play with the signature field and checks to trigger win10 or so, which maybe is the problem. Example output

```
appcompatcache v.20200428
(System) Parse files from System hive AppCompatCache
ControlSet001\Control\Session Manager\AppCompatCache
LastWrite Time: 2021-06-08 08:09:37Z
Signature: 0x80
SYSVOL\Program Files\Sysinternals\efsdump.exe  2006-11-01 13:05:23
SYSVOL\Windows\System32\sppsvc.exe  2015-05-01 01:13:15
...
```

The sig check is here: https://github.com/keydet89/RegRipper3.0/blob/master/plugins/appcompatcache.pl#L119 

Maybe only the executed field (`$files{$i}{executed} = 1 if ($f0 & 0x2);`) is missing for some of the signatures (`appWin8` among others): https://github.com/keydet89/RegRipper3.0/blob/master/plugins/appcompatcache.pl#L291 

Executed flag is also missing for Win10: https://github.com/keydet89/RegRipper3.0/blob/master/plugins/appcompatcache.pl#L374

**Comment by Karneades** [comment]
Hi @keydet89 - I wasn't able to fix the plugin to have the executed flag in the output. Are you willing to invest time to fix that?

**Comment by keydet89** [comment]
At 0:42 in this YouTube video, there's a slide, and one of the bullets states that Windows "had an "execution flag"...".

If you have the information for how to retrieve the 'executed flag' from Win10 and Windows Server 2012, I can see about investing the time to address it, yes.

**Comment by Karneades** [comment]
I don't have this information, thanks anyways.
