### ISSUE TITLE
run.pl TLN support

### ISSUE THREAD

**Issue by Zer0-Tolerance** [keydet89/RegRipper3.0#53]
Hi Harlan,
During an investigation I've noticed the registry timeline is missing entries related to persistence via autoruns via soft or user. 
Any plan to update it or shall I do a PR request ?

**Comment by keydet89** [comment]
Sorry, I'm not sure I follow what you mean.

What does "missing entries related to persistence via autoruns" mean?

For the Run key, there's nothing that ties a specific value to the LastWrite time of the key, so using regtime.exe to create a timeline from Reg key LastWrite times would suffice.

**Comment by Zer0-Tolerance** [comment]
Sorry I wasn't clear, I mean when creating the registry timeline I'm using the -aT option to get the TLN format from all hives available. When reviewing it would be useful to know that the run keys from ntuser.dat or software were modified maybe even include the current content of the key in the description field ? This is similar to what the cred.pl is doing (when using -aT) which is adding to the timeline the lastwrite of a key related to cleartext credentials storage.
  
Maybe it's just a bug because behavior of this plugin should be identical to cred.pl when used with -aT ?

**Comment by keydet89** [comment]
"...When reviewing it would be useful to know that the run keys from ntuser.dat or software were modified..."

Ok, so, there's no "run_tln.pl" plugin. To get *just* the key LastWrite times, use regtime.exe, from the Tools repo. 

The plugins run via the "-aT" switch, for the most part, collect time stamp information from values (either names or data), which is not available via regtime.exe.

**Comment by Zer0-Tolerance** [comment]
Ok so you don't think it's useful to add run_tln.pl  to have the same behavior as cred.pl because the info if available with regtime ? (I'm on OSX so not using regtime.exe)

**Comment by keydet89** [comment]
> ...you don't think it's useful to add run_tln.pl... 

It's not a matter of me thinking that it's useful or not...RR was intended from the beginning to be a community-based and community-supported tool. If you think it's useful, that's enough to warrant the plugin being created, right?

> I'm on OSX so not using regtime.exe

All tools ship with Perl source and EXE:
https://github.com/keydet89/Tools/blob/master/source/regtime.pl

**Comment by Zer0-Tolerance** [comment]
Thanks for the link for regtime and I can't agree more about the community and regripper is really a great tool ! 
I'll create the tln version.
