### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by i3v** [keydet89/RegRipper3.0#62]
I'd suggest to replace 

```
which is included in [Eric's Registry Explorer/RECmd](https://f001.backblazeb2.com/file/EricZimmermanTools/RegistryExplorer_RECmd.zip).
```
[here](https://github.com/keydet89/RegRipper3.0/blob/cee174fb6f137b14c426e97d17945ddee0d31051/README.md?plain=1#L26) (which is apparently broken), with a hopefully more stable url:
```
which is included in [Eric's Registry Explorer/RECmd](https://ericzimmerman.github.io/).
```
PS. Many thanks for providing that link - it was really helpful, at least in my case.

**Comment by Karneades** [comment]
> I'd suggest to replace
> 
> ```
> which is included in [Eric's Registry Explorer/RECmd](https://f001.backblazeb2.com/file/EricZimmermanTools/RegistryExplorer_RECmd.zip).
> ```
> 
> [here](https://github.com/keydet89/RegRipper3.0/blob/cee174fb6f137b14c426e97d17945ddee0d31051/README.md?plain=1#L26) (which is apparently broken), with a hopefully more stable url:
> 
> ```
> which is included in [Eric's Registry Explorer/RECmd](https://ericzimmerman.github.io/).
> ```
> 
> PS. Many thanks for providing that link - it was really helpful, at least in my case.

I suggest to open a pull request for such suggestion next time ;) Did it now.
